package com.mr3y.ludi.shared.ui.resources

import cafe.adriel.lyricist.LyricistStrings

@LyricistStrings(languageTag = "en", default = true)
val EnLudiStrings = LudiStrings(
    on_boarding_games_page_title = "Tell us about your favourite games",
    on_boarding_genres_page_title = "What are your favourite game genres",
    genres_page_genre_on_state_desc = { "Unselect genre %s".frmt(it) },
    genres_page_genre_off_state_desc = { "Select genre %s".frmt(it) },
    games_page_clear_search_query_desc = "Clear search query",
    games_page_search_field_desc = "Search for a specific game",
    games_page_game_content_desc = { name, rate ->  "%s, Rated: %.2f stars".frmt(name, rate) },
    games_page_game_on_state_desc = { "Remove %s from your favourite games".frmt(it) },
    games_page_game_off_state_desc = { "Add %s to your favourite games".frmt(it) },
    data_sources_page_data_source_on_state_desc = { "Unfollow %s RSS feed".frmt(it) },
    data_sources_page_data_source_off_state_desc = { "Follow %s RSS feed".frmt(it) },
    on_boarding_data_sources_page_title = "Follow your favorite news sources",
    on_boarding_secondary_text = "You can always change that later",
    on_boarding_fab_state_continue = "Continue",
    on_boarding_fab_state_continue_state_desc = "Continue",
    on_boarding_fab_state_skip = "Skip",
    on_boarding_fab_state_skip_state_desc = "Skip Onboarding and navigate to home screen",
    on_boarding_fab_state_finish = "Finish",
    on_boarding_fab_state_finish_state_desc = "Save my preferences and finish Onboarding",
    games_page_selected_label = "Selected",
    games_page_suggestions_label = "Suggestions",
    discover_page_search_field_placeholder = "What are you looking for?",
    discover_page_search_field_content_description = "Search for a specific game",
    discover_page_filter_icon_content_description = "Apply some filters to your search query to fine tune the results",
    discover_page_game_not_rated_content_description = { name, genre, platforms -> "%s is %s genre game, available for %s".frmt(name, genre, platforms) },
    discover_page_game_rated_content_description = { name, genre, rate, platforms -> "%s is %s genre game rated: %.2f stars, available for %s".frmt(name, genre, rate, platforms) },
    discover_page_filters_sheet_close_content_description = "Close filters sheet",
    filter_chip_on_state_desc = { "Unselect %s".frmt(it) },
    filter_chip_off_state_desc = { "Select %s".frmt(it) },
    news_page_filter_icon_content_description = "Customize news feed",
    news_page_article_content_description = { title, author, source -> "%s\nPublished by %s on %s".frmt(title, author, source) },
    news_page_new_release_content_description = { name, date -> "%s is expected to have a new release on %s".frmt(name, date) },
    deals_page_tab_on_state_desc = { "Currently you\'re on %s tab".frmt(it) },
    deals_page_tab_off_state_desc = { "Select %s tab".frmt(it) },
    deals_page_search_field_content_description = "Search for a specific deal or game",
    deals_page_deal_content_description = { name, newPrice, oldPrice, savings -> "Claim $name game at ${newPrice.roundToTwoDecimalDigits()} bucks instead of ${oldPrice.roundToTwoDecimalDigits()} and save ${savings.roundToTwoDecimalDigits()} percent" },
    deals_page_giveaway_content_description = { "Claim %s game for free for a limited time, enjoy the offer before it expires".frmt(it) },
    deals_page_filters_sheet_close_content_description = "Close filters sheet",
    deals_label = "Deals",
    giveaways_label = "Giveaways",
    close_filters = "Close",
    deals_search_filter_bar_placeholder = "Search for a specific deal",
    deals_filter_icon_content_description = "Show filters",
    settings_page_theme_on_state_desc = { "Currently app theme is set to %s".frmt(it) },
    settings_page_theme_off_state_desc = { "Select %s Theme".frmt(it) },
    settings_page_dynamic_colors_off_content_description = "Dynamic colors feature isn\'t available for your current Android OS version, Update to Android 12 or later to enable it.",
    settings_page_dynamic_colors_on_content_description = "Material You dynamic colors feature",
    settings_page_dynamic_colors_on_state_desc = "Disable Dynamic colors",
    settings_page_dynamic_colors_off_state_desc = "Enable Dynamic colors",
    settings_page_preference_content_description = { "Navigate to see your %s".frmt(it) },
    edit_preferences_page_confirm_button_content_description = "Save my preferences",
    edit_preferences_page_game_content_description = { "Remove %s from my favourites".frmt(it) },
    edit_preferences_page_genre_on_state_desc = { "Remove %s Genre from my favourites".frmt(it) },
    edit_preferences_page_genre_off_state_desc = { "Add %s Genre to my favourites".frmt(it) },
    now = "now",
    news_no_releases_to_show = "No New Releases to show",
    news_no_news_to_show = "No New News to show",
    news_no_reviews_to_show = "No New Reviews to show",
)
