package com.mr3y.ludi.ui.theme

import androidx.compose.ui.graphics.Color

// val RossoCorsa900 = Color(0xFFD90000)
// val ElectricRed800 = Color(0xFFE31903)
val md_theme_light_primary = Color(0xFFBD0B29)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFFFFDAD8)
val md_theme_light_onPrimaryContainer = Color(0xFF410007)
val md_theme_light_secondary = Color(0xFFBD0B29)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFFFDAD8)
val md_theme_light_onSecondaryContainer = Color(0xFF410007)
val md_theme_light_tertiary = Color(0xFF006491)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFFC9E6FF)
val md_theme_light_onTertiaryContainer = Color(0xFF001E2F)
val md_theme_light_error = Color(0xFF8D4F00)
val md_theme_light_errorContainer = Color(0xFFFFDCC0)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_onErrorContainer = Color(0xFF2E1600)
val md_theme_light_background = Color(0xFFFDFBFF)
val md_theme_light_onBackground = Color(0xFF001B3D)
val md_theme_light_surface = Color(0xFFFDFBFF)
val md_theme_light_onSurface = Color(0xFF001B3D)
val md_theme_light_surfaceVariant = Color(0xFFF4DDDC)
val md_theme_light_onSurfaceVariant = Color(0xFF524342)
val md_theme_light_outline = Color(0xFF857372)
val md_theme_light_inverseOnSurface = Color(0xFFECF0FF)
val md_theme_light_inverseSurface = Color(0xFF003062)
val md_theme_light_inversePrimary = Color(0xFFFFB3B1)
val md_theme_light_shadow = Color(0xFF000000)
val md_theme_light_surfaceTint = Color(0xFFBD0B29)
val md_theme_light_outlineVariant = Color(0xFFD7C1C0)
val md_theme_light_scrim = Color(0xFF000000)

val md_theme_dark_primary = Color(0xFFFFB3B1)
val md_theme_dark_onPrimary = Color(0xFF680010)
val md_theme_dark_primaryContainer = Color(0xFF92001B)
val md_theme_dark_onPrimaryContainer = Color(0xFFFFDAD8)
val md_theme_dark_secondary = Color(0xFFFFB3B1)
val md_theme_dark_onSecondary = Color(0xFF680010)
val md_theme_dark_secondaryContainer = Color(0xFF92001B)
val md_theme_dark_onSecondaryContainer = Color(0xFFFFDAD8)
val md_theme_dark_tertiary = Color(0xFF8ACEFF)
val md_theme_dark_onTertiary = Color(0xFF00344E)
val md_theme_dark_tertiaryContainer = Color(0xFF004B6F)
val md_theme_dark_onTertiaryContainer = Color(0xFFC9E6FF)
val md_theme_dark_error = Color(0xFFFFB877)
val md_theme_dark_errorContainer = Color(0xFF6C3A00)
val md_theme_dark_onError = Color(0xFF4B2700)
val md_theme_dark_onErrorContainer = Color(0xFFFFDCC0)
val md_theme_dark_background = Color(0xFF001B3D)
val md_theme_dark_onBackground = Color(0xFFD6E3FF)
val md_theme_dark_surface = Color(0xFF001B3D)
val md_theme_dark_onSurface = Color(0xFFD6E3FF)
val md_theme_dark_surfaceVariant = Color(0xFF524342)
val md_theme_dark_onSurfaceVariant = Color(0xFFD7C1C0)
val md_theme_dark_outline = Color(0xFFA08C8B)
val md_theme_dark_inverseOnSurface = Color(0xFF001B3D)
val md_theme_dark_inverseSurface = Color(0xFFD6E3FF)
val md_theme_dark_inversePrimary = Color(0xFFBD0B29)
val md_theme_dark_shadow = Color(0xFF000000)
val md_theme_dark_surfaceTint = Color(0xFFFFB3B1)
val md_theme_dark_outlineVariant = Color(0xFF524342)
val md_theme_dark_scrim = Color(0xFF000000)

// Custom colors
val light_star = Color(0xFFFFE086)
val light_onstar = Color(0xFF231B00)
val dark_star = Color(0xFFE9C349)
val dark_onstar = Color(0xFF3C2F00)

val seed = Color(0xFFD72638)
// another secondary color to consider
// val Blue = Color(0xFF12355b)
