package com.mr3y.ludi.shared.core.database

// kotlin-inject fails to resolve types generated by sqlDelight,
// As a workaround we have to wrap those types to make them resolvable.
// See: https://github.com/evant/kotlin-inject/issues/316

@JvmInline
value class LudiDatabaseWrapper(val value: LudiDatabase)
