package com.mr3y.ludi.shared.ui.datastore

import androidx.datastore.core.DataStore
import com.mr3y.ludi.datastore.model.FollowedNewsDataSources
import com.mr3y.ludi.datastore.model.UserFavouriteGames
import com.mr3y.ludi.datastore.model.UserFavouriteGenres

// kotlin-inject fails to resolve types generated by wire,
// As a workaround we have to wrap those types to make them resolvable.
// See: https://github.com/evant/kotlin-inject/issues/316

@JvmInline
value class UserFavoriteGamesDataStore(val value: DataStore<UserFavouriteGames>)

@JvmInline
value class FollowedNewsDataSourcesDataStore(val value: DataStore<FollowedNewsDataSources>)

@JvmInline
value class UserFavoriteGenresDataStore(val value: DataStore<UserFavouriteGenres>)
