name: Release a new version

on:
  push:
    tags:
      - 'v*'
      - '!v*-desktop'

jobs:
  release:
    runs-on: windows-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2.7.0

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build changelog
        id: build_changelog
        uses: mikepenz/release-changelog-builder-action@v4
        with:
          configuration: "changelog_config.json"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Configure Keystore
        shell: bash
        run: |
          echo '${{ secrets.KEYSTORE_FILE }}' | base64 -d > ./androidApp/ludi_keystore.jks
          echo "storeFile=./ludi_keystore.jks" >> keystore.properties
          echo "keyAlias=$KEYSTORE_KEY_ALIAS" >> keystore.properties
          echo "storePassword=$KEYSTORE_STORE_PASSWORD" >> keystore.properties
          echo "keyPassword=$KEYSTORE_KEY_PASSWORD" >> keystore.properties
        env:
          KEYSTORE_KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          KEYSTORE_KEY_PASSWORD: ${{ secrets.STORE_KEY_PASSWORD }}
          KEYSTORE_STORE_PASSWORD: ${{ secrets.STORE_KEY_PASSWORD }}

      - name: Build & Publish Release (.aab) bundle to Play console
        run: ./gradlew bundleRelease publishReleaseBundle
        env:
          ANDROID_PUBLISHER_CREDENTIALS: ${{ secrets.ANDROID_PUBLISHER_CREDENTIALS }}

      - name: Build release APK
        run: ./gradlew assembleRelease --stacktrace

      - name: Upload release APK
        uses: actions/upload-artifact@v3
        with:
          name: app-release
          path: ./androidApp/build/outputs/apk/release/androidApp-release.apk

      - uses: ncipollo/release-action@v1
        with:
          artifacts: "./androidApp/build/outputs/apk/release/androidApp-release.apk"
          body: ${{ steps.build_changelog.outputs.changelog }}
