name: Release a new Desktop app version

on:
  push:
    tags:
      - 'v*-desktop'

jobs:
  release:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2.7.0

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build Desktop release binary
        run: ./gradlew packageDistributionForCurrentOS --stacktrace

      - name: Upload Desktop release binary
        uses: actions/upload-artifact@v3
        with:
          name: desktopApp-${{ matrix.os }}-release
          path: desktopApp/build/compose/binaries/main/

      - uses: ncipollo/release-action@v1
        with:
          name: ${{ matrix.os }}-${{ github.ref_name }}-release
          artifacts: "./desktopApp/build/compose/binaries/main/*/*.*"
          generateReleaseNotes: true